Repository gogs/gogs, pull requests merged in 2020-04, with the labels that each got.

#6058 conf: clearer doc comments for mirror config options
  conf/app.ini
  internal/assets/conf/conf_gen.go
Labels: status: needs followup

#6056 db: include the Team ID in the error message
  internal/db/error.go
  internal/db/org_team.go
Labels: status: needs feedback

#6068 docker: fix the bug of using root account to create `/data/*` directory
  docker/s6/gogs/run
  docker/s6/gogs/setup
  docker/start.sh
Labels: status: needs followup

#6095 ssh: improve env command processing
  internal/ssh/ssh.go
Labels: status: reviewed

#6101 api: add admin endpoint to get team members
  internal/route/api/v1/admin/org_team.go
  internal/route/api/v1/api.go
Labels: status: needs followup, status: reviewed

#6122 db: remove `db.User.LoginType` field
  internal/db/login_source.go
  internal/db/user.go
  internal/db/users.go
  internal/route/admin/users.go
  internal/route/api/v1/admin/user.go
Labels: status: needs followup, status: reviewed
